logging:
  level:
    org.springframework.security: DEBUG

spring:
  config:
    import:
      - classpath:/app/jwt/application-jwt.yml
      - classpath:/app/redis/application-redis-local.yml
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            #redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            #redirect-uri: "http://localhost:8080/swagger-ui/oauth2-redirect.html"
            redirect-uri: "https://getpostman.com/oauth2/callback"
            scope: name, email, mobile
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response

